## Configuration for single eureka server, and no spring config
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/

server:
  port: 8020
  
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'